name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs automatically every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Custom Synthwave Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ShubhamKumar1703
          # Upgraded with custom Synthwave hex colors
          outputs: |
            dist/snake.svg?color_snake=#00FFCC&color_dots=#161B22,#8A2BE2,#FF1493,#FF00FF,#00FFFF
            
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
